name: Terraform Apply a Pull Request
description: This workflow will run terraform apply on the merge commit of a pull request and upload the output to S3 for persistence.
author: jrafferty@tamu.edu

inputs:
  debug:
    description: Debug workflow with tmate if an error occurs
    required: false
    default: "false"
  GITHUB_TOKEN:
    description: GitHub token for access to the pull request
    required: true
  working-directory:
    description: Working directory for the `run` actions
    required: false
    default: ""
  terraform-version:
    description: Version of terraform to install
    required: false
    default: latest
  terraform-workspace:
    description: Terraform workspace to select. Must already exist
    required: false
    default: default
  terraform-init-flags:
    description: CLI flags to use with terraform init
    required: false
    default: ""
  terraform-apply-flags:
    description: CLI flags to use with terraform apply
    required: false
    default: ""
  s3-bucket:
    description: Override s3 bucket to upload output to. Defaults to the same as the state backend.
    required: false
    default: ""
  s3-key:
    description: Override s3 object key to upload output to. Defaults to a subdirectory of the statefile key.
    required: false
    default: ""
  pr-id:
    description: Associate the run with a specific pull request id. Defaults to finding the ID from the merge commit.
    required: false
    default: ""
  auto-approve:
    description: Auto approve terraform apply
    required: false
    default: "true"

outputs:
  apply_output:
    description: The terraform apply output
    value: ${{ steps.tf-via-pr.outputs.tf_output }}
  s3_path:
    description: The S3 URL of the uploaded log file
    value: ${{ steps.tf-via-pr.outputs.s3_url }}

runs:
  using: composite
  steps:
    - name: Find if this push belonged to a PR
      if: github.event_name == 'push' && inputs.pr-id == ''
      uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: pr

    - name: Consolidate PR ID
      shell: bash
      id: pr_id
      run: |
        if [[ "${{ inputs.pr-id }}" != "" ]]; then
          number=${{ inputs.pr-id }}
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          if [[ "${{ steps.pr.outputs.pr_found }}" == "false" ]]; then
            echo "No PR found for this workflow run. Exiting."
            exit 1
          fi
          number=${{ steps.pr.outputs.number }}
        else
          number=${{ github.event.number }}
        fi

        echo "number=$number" >> $GITHUB_OUTPUT
        echo "This workflow run is associated with pull request ID: $number"

    - name: Run Terraform via PR
      id: tf-via-pr
      uses: OP5dev/TF-via-PR@v13.7.1
      with:
        apply: "true"
        path: ${{ inputs.working-directory }}

        terraform_version: ${{ inputs.terraform-version }}
        terraform_workspace: ${{ inputs.terraform-workspace }}
        terraform_init_cli_options: ${{ inputs.terraform-init-flags }}
        terraform_apply_cli_options: ${{ inputs.terraform-apply-flags }}

        auto_approve: ${{ inputs.auto-approve }}

        github_token: ${{ inputs.GITHUB_TOKEN }}
        pull_request_id: ${{ steps.pr_id.outputs.number }}

        s3_bucket_name: ${{ inputs.s3-bucket }}
        s3_object_key: ${{ inputs.s3-key }}

        comment_pr: "true"

        continue_on_error: "true"

    - name: Debug with TMATE if the debug environment variable is set to "true" and something failed
      if: ${{ failure() && inputs.debug == 'true' }}
      uses: mxschmitt/action-tmate@v3

    - name: Workflow Run Status
      shell: bash
      if: steps.tf-via-pr.outputs.terraform_outcome == 'failure'
      run: exit 1
